# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pytest

on: [push]

permissions:
  contents: read

jobs:
  build:

    strategy:
      matrix:
        python-version: ["3.8"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest 
        pip install pytest-cov
        pip install sphinx
        pip install nbsphinx
        pip install nbsphinx-link
        pip install pydata_sphinx_theme
        pip install .

        sudo apt-get install --no-install-recommends pandoc
        
    - name: Test with custom pytest runner
      run: |
        bash ./test.sh --cov=RMK_support --cov-config=.coveragerc . --cov-report xml

    - name: Upload code coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ${{ github.workspace }}/RMK_support/tests/coverage.xml
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)

    - name: Test documentation build
      run: |
        sphinx-apidoc -f -o docs/source/ RMK_support/
        cd docs/
        make html